name = "ifarm-core-api-dev"
main = "src/index.ts"
compatibility_date = "2026-09-02"

[vars]
APP_ENV = "development"

[env.stage]
name = "ifarm-core-api-stage"
vars = { APP_ENV = "stage" }

[env.production]
name = "ifarm-core-api"
vars = { APP_ENV = "production" }
